---
# Example playbook to perform either a splunk installation or upgrade
- hosts:
  - all
  roles:
  - ../../roles/splunk
  vars:
  - deployment_task: check_splunk.yml


- hosts:
  - licensemaster
  roles:
  - ../../roles/splunk-license-master
  vars:
  - deployment_task: add_license.yml


- hosts:
  - clustermaster
  roles:
  - ../../roles/splunk-cluster-master
  vars:
  - deployment_task: configure_cluster_master.yml

  
- hosts:
  - indexer
  roles:
  - ../../roles/splunk-indexers
  vars:
  - deployment_task: configure_cluster_indexer.yml

- hosts:
  - searchhead
  roles:
  - ../../roles/splunk-search-heads
  vars:
  - deployment_task: configure_cluster_searchhead.yml
