# Example playbook to install splunk and configure a basic SHC
# Ensure that the following vars are configured: ansible_user, ansible_ssh_private_key_file, splunk_admin_password, splunk_user_seed: true
- hosts:
    - indexer
  roles:
    - ../../roles/splunk-indexers
  vars:
    - deployment_task: configure_cluster_indexer.yml
